### ISSUE TITLE
Modifier le chemin de stylelint pour ne pas inclure les modules et vendor

### ISSUE THREAD

**Issue by DavidBilodeau1** [eckinox/eckinox-cs#1]
"lint:css": "npx stylelint --allow-empty-input \"public/css/*.css\" \"public/css/**/*.css\"",

**Comment by EmilePerron** [comment]
Fixed via le [`replicate/.stylelintignore`](../tree/main/replicate/.stylelintignore) dans 1.0.4 (et toute les versions succéquentes).
